"""File-processing coded agent — Studio Web "Coded copy of FileProcessingAgent".

Source of truth: the coded agent generated by Studio Web's "Clone as Coded
Agent" from the low-code FileProcessingAgent (solution 1823d2d6-…, project
e7b8598c-…). The pristine download is kept in ``coded-copy/``; this module is
that file with exactly one structural change: the module-level hardcoded
``llm`` is replaced by ``build_graph(llm)`` so the onboarding testcase can
inject the model built from ``model_spec`` (model + API flavor configurable).

The ``run`` adapter at the bottom uploads the test file as a real platform
attachment and invokes the generated graph — exercising the production ReAct
agent (``create_agent``) and the real *Analyze Files* internal tool.
"""

from datetime import (
    datetime,
    timezone
)
from langchain_core.messages import (
    HumanMessage,
    SystemMessage
)
from pydantic import (
    BaseModel,
    Field
)
from pydantic import (
    ConfigDict
)
from typing import (
    Sequence
)
from uipath.agent.models.agent import (
    AgentInternalToolResourceConfig
)
from uipath.agent.react import (
    AGENT_SYSTEM_PROMPT_TEMPLATE
)
from uipath.platform.attachments import (
    Attachment
)
from uipath_langchain.agent.react import (
    create_agent
)
from uipath_langchain.agent.tools.internal_tools import (
    create_internal_tool
)

from agents.utils import (
    interpolate_legacy_message
)

# Required alias for job attachment detection at runtime
__Job_attachment = Attachment

NAME = "file_processing"


# Input/Output Models
class AgentInput(BaseModel):
    model_config = ConfigDict(extra='allow')
    prompt: str = Field(..., description="The task or question to answer about the attached file.")
    fileIn: Attachment


class AgentOutput(BaseModel):
    model_config = ConfigDict(extra='allow')
    content: str | None = Field(None, description="The agent's analysis of the attached file.")


# Agent Messages Function
def create_messages(state: AgentInput) -> Sequence[SystemMessage | HumanMessage]:
    # Extract values safely from state
    fileIn = getattr(state, 'fileIn', '')
    prompt = getattr(state, 'prompt', '')

    # Apply system prompt template
    current_date = datetime.now(timezone.utc).strftime('%Y-%m-%d')
    system_prompt_content = """You are a file-processing assistant. You are given a single file (PDF or image) and a task. Use the Analyze Files tool to read the file's contents, then answer the task concisely based only on what the file contains. If the file cannot be read, say so plainly."""
    system_prompt_content = interpolate_legacy_message(system_prompt_content, state.model_dump())
    enhanced_system_prompt = (
        AGENT_SYSTEM_PROMPT_TEMPLATE
        .replace('{{systemPrompt}}', system_prompt_content)
        .replace('{{currentDate}}', current_date)
        .replace('{{agentName}}', 'Mr Assistant')
    )

    return [
        SystemMessage(content=enhanced_system_prompt),
        HumanMessage(content=interpolate_legacy_message("""{{prompt}}

{{fileIn}}""", state.model_dump())),
    ]


def build_graph(llm):
    """Build the generated agent graph for an injected model.

    Mirrors the Studio Web coded copy's module body; ``llm`` replaces the
    hardcoded ``get_chat_model(model='gpt-5.4', ...)`` so the testcase can
    exercise any model/path from ``model_spec``.
    """
    # Context Grounding Tool: analyze_files
    analyze_files_config = AgentInternalToolResourceConfig(
        name='Analyze Files',
        description='Analyze one or more files with an LLM to extract, synthesize, or answer queries about their content.',
        type='Internal',
        input_schema={'type': 'object', 'properties': {'attachments': {'type': 'array', 'items': {'$ref': '#/definitions/job-attachment'}, 'description': 'Array of files, documents, images, or other attachments to process'}, 'analysisTask': {'type': 'string', 'description': 'The task, question, or instruction for processing the files'}}, 'required': ['attachments', 'analysisTask'], 'definitions': {'job-attachment': {'type': 'object', 'properties': {'ID': {'type': 'string', 'description': 'Orchestrator attachment key'}, 'FullName': {'type': 'string', 'description': 'File name'}, 'MimeType': {'type': 'string', 'description': 'MIME type, e.g. "application/pdf", "image/png"'}, 'Metadata': {'type': 'object', 'description': 'Dictionary<string, string> of metadata', 'additionalProperties': {'type': 'string'}}}, 'required': ['ID'], 'x-uipath-resource-kind': 'JobAttachment'}}},
        output_schema={'type': 'object', 'properties': {'analysis': {'type': 'string', 'description': 'Analysis result of the attachments'}}, 'required': ['analysis']},
        properties={'requireConversationalConfirmation': False, 'toolType': 'analyze-attachments'},
        arguments={},
        argument_properties={}
    )
    analyze_files_tool = create_internal_tool(analyze_files_config, llm)

    # Collect all tools
    tools = []
    tools.append(analyze_files_tool)

    # Create agent graph
    return create_agent(model=llm, messages=create_messages, tools=tools, input_schema=AgentInput, output_schema=AgentOutput)


async def _upload_attachment(file_info) -> Attachment:
    """Fetch the test file and register it as a platform attachment."""
    import httpx
    from uipath.platform import UiPath
    from uipath_langchain._utils import get_httpx_client_kwargs

    async with httpx.AsyncClient(**get_httpx_client_kwargs()) as client:
        response = await client.get(file_info.url)
        response.raise_for_status()
        content = response.content

    sdk = UiPath()
    attachment_id = await sdk.attachments.upload_async(
        name=file_info.name, content=content
    )
    return Attachment(
        id=attachment_id,
        full_name=file_info.name,
        mime_type=file_info.mime_type,
    )


async def run(model, prompt: str, files) -> str:
    """Testcase adapter: run the generated graph over one attached file.

    Returns ``"✓"`` or ``"✗ ..."`` per the onboarding cell contract.
    """
    if not files:
        return "✗ file_processing requires a file"
    attachment = await _upload_attachment(files[0])
    graph = build_graph(model)
    if hasattr(graph, "compile"):  # create_agent returns an uncompiled StateGraph
        graph = graph.compile()
    result = await graph.ainvoke(AgentInput(prompt=prompt, fileIn=attachment))
    content = (result or {}).get("content") if isinstance(result, dict) else getattr(result, "content", None)
    if content and str(content).strip():
        return "✓"
    return "✗ empty response"
