def get_preload_modules() -> list[str]:
    return [
        # --- uipath ---
        "uipath.core",
        "uipath.platform",
        "uipath.tracing",
        "uipath.utils",
        "uipath_agents.agent_graph_builder",
        # --- uipath_langchain ---
        "uipath_langchain.agent.guardrails",
        "uipath_langchain.chat.bedrock",
        "uipath_langchain.chat.chat_model_factory",
        "uipath_langchain.chat.models",
        "uipath_langchain.chat.openai",
        "uipath_langchain.chat.supported_models",
        "uipath_langchain.chat.types",
        "uipath_langchain.chat.vertex",
        # --- langchain ---
        "langchain_core.prompts.base",
        "langchain_core.prompts.chat",
        "langchain_core.prompts.message",
        "langchain_core.prompts.prompt",
        "langchain_core.tracers.context",
        "langchain_mcp_adapters.tools",
        # --- langchain_openai ---
        "langchain_openai.chat_models.base",
        "langchain_openai.chat_models.azure",
        "langchain_openai.chat_models._client_utils",
        "langchain_openai.embeddings.base",
        "langchain_openai.llms.base",
        "langchain_openai.llms.azure",
        # --- langchain_aws ---
        "langchain_aws.chat_models.bedrock",
        "langchain_aws.chat_models.bedrock_converse",
        "langchain_aws.data",
        "langchain_aws.embeddings",
        "langchain_aws.function_calling",
        "langchain_aws.llms.bedrock",
        "langchain_aws.retrievers.bedrock",
        "langchain_aws.retrievers.kendra",
        "langchain_aws.retrievers.s3_vectors",
        # --- openai ---
        "openai._extras",
        "openai.lib.streaming.chat._types",
        "openai.resources.chat",
        "openai.types.audio.transcription",
        "openai.types.beta.chatkit.chatkit_thread_item_list",
        "openai.types.beta.realtime.conversation_item_create_event_param",
        "openai.types.beta.realtime.response_audio_done_event",
        "openai.types.beta.realtime.response_create_event",
        "openai.types.beta.realtime.session_create_params",
        "openai.types.beta.realtime.transcription_session_updated_event",
        "openai.types.beta.threads.runs",
        "openai.types.evals.run_create_params",
        "openai.types.evals.run_retrieve_response",
        "openai.types.fine_tuning.job_create_params",
        "openai.types.fine_tuning.alpha.grader_validate_params",
        "openai.types.skills.version_create_params",
        "openai.types.vector_stores.vector_store_file_batch",
        # --- google / vertex ---
        "google.genai.types",
        "google.genai.client",
        "google.genai.tunings",
        "google.genai._transformers",
        "google.genai._interactions.types",
        "google.genai._interactions.types.content_param",
        "google.genai._interactions.types.model_param",
        "google.genai._interactions.types.url_context_call_arguments",
        "google.genai._interactions._models",
        "google.auth.transport._http_client",
        "langchain_google_genai.chat_models",
        "langchain_google_genai.data",
        "langchain_google_genai.llms",
        # --- boto3 / botocore / AWS ---
        "boto3.resources.action",
        "botocore.client",
        "botocore.compat",
        "botocore.configloader",
        "botocore.credentials",
        "botocore.discovery",
        "botocore.docs",
        "botocore.handlers",
        "botocore.monitoring",
        "botocore.response",
        "botocore.session",
        "jmespath",
        "s3transfer.compat",
        "s3transfer.exceptions",
        "s3transfer.manager",
        "s3transfer.upload",
        # --- mcp ---
        "mcp.client.streamable_http",
        # --- observability ---
        "applicationinsights",
        "azure.monitor.opentelemetry.exporter",
        "opentelemetry.context",
        "opentelemetry.instrumentation.aiohttp_client",
        "opentelemetry.instrumentation.httpx",
        "opentelemetry.sdk.trace.export",
        # --- networking / serialization ---
        "bidict",
        "h11",
        "httpcore",
        "httpx",
        "websockets.asyncio.connection",
        "websockets.client",
        "jwt",
        "pydantic",
        "socketio",
        "truststore",
        "yaml",
        # --- stdlib / native ---
        "dateutil.parser",
        "difflib",
        "gzip",
        "multiprocessing.managers",
        "numpy._core",
        "numpy._typing",
        "numpy.lib",
        "numpy.linalg",
    ]
