"""Span processor for marking spans to be filtered by exporters."""

import re

from opentelemetry.context import Context
from opentelemetry.sdk.trace import ReadableSpan, Span, SpanProcessor

from .tracing import is_openinference_span

# UUID pattern for filtering auto-generated spans
_UUID_PATTERN = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    re.IGNORECASE,
)

# Span names to filter (noise from auto-instrumentation and LangChain)
_FILTERED_SPAN_NAMES = frozenset({"Evaluators", "evaluate_guardrail"})

# SDK internal spans use run_type="uipath" attribute
_SDK_INTERNAL_RUN_TYPE = "uipath"


def _is_sdk_internal_span(span: Span) -> bool:
    """Check if span is from uipath-python SDK.

    SDK methods decorated with @traced(run_type="uipath") set this attribute.
    """
    attrs = span.attributes
    return attrs is not None and attrs.get("run_type") == _SDK_INTERNAL_RUN_TYPE


def _should_filter_span(span: Span) -> bool:
    """Check if span should be filtered based on name.

    Filters spans with:
    - GUID/UUID names (auto-generated by LangChain)
    - Names in _FILTERED_SPAN_NAMES
    """
    span_name = span.name

    if span_name in _FILTERED_SPAN_NAMES:
        return True

    if _UUID_PATTERN.match(span_name):
        return True

    return False


class SourceMarkerProcessor(SpanProcessor):
    """Marks spans for filtering by exporters.

    Tags the following spans with telemetry.filter="drop":
    - OpenInference spans (they go to AppInsights instead of LLMOps)
    - SDK internal spans (run_type="uipath" attribute)
    - Spans with GUID names or noise names like "Evaluators", "evaluate_guardrail"

    The LlmOpsHttpExporter skips spans marked for drop.
    """

    FILTER_ATTRIBUTE = "telemetry.filter"

    def on_start(self, span: Span, parent_context: Context | None = None) -> None:
        """Mark spans to be dropped by LlmOpsHttpExporter."""
        if is_openinference_span(span) or _is_sdk_internal_span(span):
            span.set_attribute(self.FILTER_ATTRIBUTE, "drop")
            return

        if _should_filter_span(span):
            span.set_attribute(self.FILTER_ATTRIBUTE, "drop")

    def on_end(self, span: ReadableSpan) -> None:
        """No-op on span end."""
        pass

    def shutdown(self) -> None:
        """No-op shutdown."""
        pass

    def force_flush(self, timeout_millis: int | None = None) -> bool:
        """No-op flush."""
        return True
