"""Span processor for marking spans to be filtered by exporters."""

import re

from opentelemetry.context import Context
from opentelemetry.sdk.trace import ReadableSpan, Span, SpanProcessor

from .tracing import is_openinference_span

# UUID pattern for filtering auto-generated spans
_UUID_PATTERN = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    re.IGNORECASE,
)

# Span names to filter
_FILTERED_SPAN_NAMES = frozenset({"Evaluators", "root"})


def _should_filter_span(span: Span) -> bool:
    """Check if span should be filtered based on name.

    Filters spans with:
    - GUID/UUID names (auto-generated by LangChain)
    - Name "Evaluators" or "root"
    """
    span_name = span.name

    if span_name in _FILTERED_SPAN_NAMES:
        return True

    if _UUID_PATTERN.match(span_name):
        return True

    return False


class SourceMarkerProcessor(SpanProcessor):
    """Marks spans for filtering by exporters.

    Tags the following spans with telemetry.filter="drop":
    - OpenInference spans (they go to AppInsights instead of LLMOps)
    - Spans with GUID names or named "Evaluators" or "root"

    The LlmOpsHttpExporter skips spans marked for drop.
    """

    FILTER_ATTRIBUTE = "telemetry.filter"

    def on_start(self, span: Span, parent_context: Context | None = None) -> None:
        """Mark spans to be dropped by LlmOpsHttpExporter."""
        if is_openinference_span(span):
            span.set_attribute(self.FILTER_ATTRIBUTE, "drop")
            return

        if _should_filter_span(span):
            span.set_attribute(self.FILTER_ATTRIBUTE, "drop")

    def on_end(self, span: ReadableSpan) -> None:
        """No-op on span end."""
        pass

    def shutdown(self) -> None:
        """No-op shutdown."""
        pass

    def force_flush(self, timeout_millis: int | None = None) -> bool:
        """No-op flush."""
        return True
