[project]
name = "company-research-agent"
version = "0.0.1"
description = "Company research agent with Tavily web search"
authors = [{ name = "John Doe", email = "john.doe@myemail.com" }]

requires-python = ">=3.11"
dependencies = [
    "uipath-langchain",
    "langgraph>=1.0.1",
    "langchain-community>=0.3.21",
    "ddgs>=9.6.1",
]

[project.optional-dependencies]
dev = ["mypy>=1.11.1", "ruff>=0.6.1"]

[tool.uv.sources]
uipath-langchain = { path = "../../", editable = true }

[build-system]
requires = ["setuptools>=73.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"*" = ["py.typed"]

[tool.ruff]
lint.select = [
    "E",    # pycodestyle
    "F",    # pyflakes
    "I",    # isort
    "D",    # pydocstyle
    "D401", # First line should be in imperative mood
    "T201",
    "UP",
]
lint.ignore = [
    "UP006",
    "UP007",
    "UP035",
    "D417",
    "E501",
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D", "UP"]

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true
