name: Build

on:
  workflow_run:
    workflows: ["Lint", "Commit Lint", "Test"]
    types:
      - completed

jobs:
  build:
    name: Build and publish
    runs-on: "ubuntu-24.04"
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main' }}

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Setup venv
        run: |
          uv venv
          uv sync --all-extras

      - name: Build
        run: |
          uv build

      - name: Check if version in pyproject.toml was modified
        id: check_version
        run: |
          if git diff --name-only ${{ github.sha }} ${{ github.event.before }} | grep -q 'pyproject.toml'; then
            echo "modified=true" >> $GITHUB_OUTPUT
          else
            echo "modified=false" >> $GITHUB_OUTPUT
          fi

      - name: "Publish"
        if: ${{ steps.check_version.outputs.modified }} == 'true'
        run: |
          uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
