name: Commit Lint

on:
  workflow_call

jobs:
  commitlint:
    name: Commit Lint
    runs-on: uipath-ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4.4.0
        with:
          fetch-depth: 0

      - name: Validate PR commits with commitlint
        uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed  # v6
