name: Retrieval Chain CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'samples/retrieval-chain/**'
  pull_request:
    branches: [ main ]

jobs:
  test-retrieval-chain:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        docker build -t retrieval-chain:test \
          --build-arg CLIENT_ID="${{ secrets.UIPATH_CLIENT_ID }}" \
          --build-arg CLIENT_SECRET="${{ secrets.UIPATH_CLIENT_SECRET }}" \
          --build-arg BASE_URL="${{ secrets.UIPATH_BASE_URL }}" \
          .
      working-directory: ./samples/retrieval-chain
    
    - name: Test retrieval chain with default parameters
      run: |
        cd samples/retrieval-chain
        docker run --rm \
          -e CLIENT_ID="${{ secrets.UIPATH_CLIENT_ID }}" \
          -e CLIENT_SECRET="${{ secrets.UIPATH_CLIENT_SECRET }}" \
          -e BASE_URL="${{ secrets.UIPATH_BASE_URL }}" \
          retrieval-chain:test
    
    - name: Test retrieval chain with custom parameters
      if: github.event_name == 'workflow_dispatch'
      run: |
        cd samples/retrieval-chain
        docker run --rm \
          -e CLIENT_ID="${{ secrets.UIPATH_CLIENT_ID }}" \
          -e CLIENT_SECRET="${{ secrets.UIPATH_CLIENT_SECRET }}" \
          -e BASE_URL="${{ secrets.UIPATH_BASE_URL }}" \
          retrieval-chain:test \
          /app/startup.sh --index_name "${{ github.event.inputs.index_name }}" --query "${{ github.event.inputs.query }}" --k ${{ github.event.inputs.k }}
