name: Test

on:
  push:
    branches:
      - 'refs/heads/main'
      - 'refs/heads/**'

  pull_request_review:
    types: [submitted]

jobs:
  test:
    name: Test
    runs-on: "ubuntu-24.04"
    if: ${{ (github.event_name == 'pull_request_review' && github.event.review.state == 'approved') || (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.event.pull_request.state == 'open')) }}

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: "Setup venv"
        run: |
          uv venv
          uv sync --all-extras

      - name: "Run tests"
        run: |
          uv run pytest
        env:
          UIPATH_URL: ${{ secrets.UIPATH_URL }}
          UIPATH_CLIENT_ID: ${{ secrets.UIPATH_CLIENT_ID }}
          UIPATH_CLIENT_SECRET: ${{ secrets.UIPATH_CLIENT_SECRET }}

